name: OTF Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Functional Test (${{ matrix.browser }})
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        browser: [firefox, chrome, edge]

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Create isolated network
        run: docker network create --driver bridge isolated

      - name: Deploy AUT
        run: docker build -t my-php-site:latest .

      - name: Run AUT
        run: docker run --network=isolated -p 80:80 --name docker-apache -d my-php-site:latest

      - name: Start Selenium (${{ matrix.browser }})
        run: |
          if [ "${{ matrix.browser }}" = "firefox" ]; then
            docker run --network=isolated -d -p 4444:4444 -p 7900:7900 -v /dev/shm:/dev/shm --name selenium selenium/standalone-firefox:latest
          elif [ "${{ matrix.browser }}" = "chrome" ]; then
            docker run --network=isolated -d -p 4444:4444 -p 7900:7900 -v /dev/shm:/dev/shm --name selenium selenium/standalone-chrome:latest
          else
            docker run --network=isolated -d -p 4444:4444 -p 7900:7900 -v /dev/shm:/dev/shm --name selenium selenium/standalone-edge:latest
          fi

      - name: Wait for Selenium Hub
        run: sh wait.sh

      - name: Install Selenium Client
        run: pip install -U selenium

      - name: Run test
        run: python tests/hello_aut.py http://docker-apache ${{ matrix.browser }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Screenshot-${{ matrix.browser }}
          path: screenshot.png

      - name: Stop AUT
        run: docker stop docker-apache
